import type * as Party from "partykit/server";
import {
  ATTACK_COOLDOWN_MS,
  GLOBAL_ATTACK_COOLDOWN_MS,
  MEETING_MS,
  MIN_PLAYERS,
  ROUND_MS,
  TAKEOVER_MS,
  normalizeName,
  type AttackKind,
  type ClientMessage,
  type ErrorCode,
  type Evidence,
  type Packet,
  type Phase,
  type Player,
  type Role,
  type RoomSnapshot,
  type RoundResult,
  type ServerMessage,
  type Vote,
} from "../lib/protocol";

/**
 * Round timings come from the shared constants, but any of them can be
 * overridden with a PartyKit var so a round can be shortened for playtesting or
 * automated tests without editing code:
 *   npm run dev:party -- --var ROUND_MS=15000
 */
function envMs(env: Party.Room["env"], key: string, fallback: number): number {
  const raw = env?.[key];
  const n = typeof raw === "string" ? Number(raw) : typeof raw === "number" ? raw : NaN;
  return Number.isFinite(n) && n > 0 ? n : fallback;
}

/** How many flagged packets the meeting shows. Newest win. */
const MAX_EVIDENCE = 40;
/** Ground truth kept for scoring flags. Bounded so a long round cannot grow it forever. */
const MAX_TRACKED_SEQS = 4000;

/**
 * One PartyKit room == one game lobby. `this.room.id` *is* the 6-char code.
 *
 * Authority model: the room server owns all shared state, and owns every secret.
 * Clients send intent, never state. Two rules carry the whole game:
 *
 *  1. Roles are delivered per-connection and never appear on a snapshot.
 *  2. The packet feed is generated by the host's browser but *distributed here*,
 *     to Benign players only. The Hacker cannot read the feed off the wire
 *     because it is never sent to them.
 */
export default class NetsleuthRoom implements Party.Server {
  constructor(readonly room: Party.Room) {}

  private players = new Map<string, Player>();
  private phase: Phase = "lobby";
  private banned = new Map<string, string>();

  /** Secret. Never serialized into a snapshot. */
  private roles = new Map<string, Role>();

  private deadline: number | null = null;
  private phaseTimer: ReturnType<typeof setTimeout> | null = null;

  /** seq -> which attack it belonged to, for scoring flags. */
  private anomalySeqs = new Map<number, AttackKind>();
  private seenSeqs: number[] = [];
  private recentPackets = new Map<number, Packet>();

  private evidence: Evidence[] = [];
  private flaggedBy = new Map<string, Set<number>>();
  private votes = new Map<string, string | null>();
  private result: RoundResult | null = null;

  private lastAttackAt = 0;
  private lastAttackByKind = new Map<AttackKind, number>();
  private attacksLaunched = 0;

  async onMessage(raw: string, sender: Party.Connection) {
    let msg: ClientMessage;
    try {
      msg = JSON.parse(raw) as ClientMessage;
    } catch {
      return this.sendError(sender, "bad_message", "Malformed message.");
    }

    switch (msg?.type) {
      case "hello":
        return this.onHello(msg, sender);
      case "kick":
        return this.onKick(msg, sender);
      case "transferHost":
        return this.onTransferHost(msg, sender);
      case "startGame":
        return this.onStartGame(sender);
      case "feed":
        return this.onFeed(msg, sender);
      case "attack":
        return this.onAttack(msg, sender);
      case "flag":
        return this.onFlag(msg, sender);
      case "vote":
        return this.onVote(msg, sender);
      default:
        return this.sendError(sender, "bad_message", "Unknown message type.");
    }
  }

  // --- lobby ---------------------------------------------------------------

  private async onHello(
    msg: Extract<ClientMessage, { type: "hello" }>,
    sender: Party.Connection,
  ) {
    const bannedBy = this.banned.get(sender.id);
    if (bannedBy !== undefined) {
      this.send(sender, { type: "kicked", byName: bannedBy });
      return sender.close();
    }

    const name = normalizeName(msg.name);
    if (!name) {
      return this.sendError(sender, "bad_message", "A display name is required.");
    }

    const wasCreated = (await this.room.storage.get<boolean>("created")) ?? false;
    if (msg.intent === "create") {
      if (!wasCreated) await this.room.storage.put("created", true);
    } else if (!wasCreated) {
      return this.sendError(
        sender,
        "room_not_found",
        `No lobby with code ${this.room.id}.`,
      );
    }

    const taken = [...this.players.values()].some(
      (p) => p.id !== sender.id && p.name.toLowerCase() === name.toLowerCase(),
    );
    if (taken) {
      return this.sendError(sender, "name_taken", `"${name}" is already in this lobby.`);
    }

    // A reconnecting player re-sends `hello`, so this is an update as often as
    // it is an insert. Preserve the existing host flag: recomputing it here
    // would silently demote a host whose socket merely blipped.
    const existing = this.players.get(sender.id);
    const isHost = existing ? existing.isHost : this.players.size === 0;
    this.players.set(sender.id, { id: sender.id, name, isHost });

    this.ensureHost();

    // Someone reconnecting mid-round needs their role back, or their screen
    // would render as a Benign monitor regardless of what they actually are.
    const role = this.roles.get(sender.id);
    if (role) this.send(sender, { type: "role", role });

    this.broadcastSnapshot();
  }

  private onKick(
    msg: Extract<ClientMessage, { type: "kick" }>,
    sender: Party.Connection,
  ) {
    const host = this.requireHost(sender);
    if (!host) return;

    if (msg.playerId === sender.id) {
      return this.sendError(sender, "bad_message", "You cannot kick yourself.");
    }

    const target = this.players.get(msg.playerId);
    if (!target) {
      return this.sendError(sender, "unknown_player", "That player already left.");
    }

    this.banned.set(target.id, host.name);
    this.players.delete(target.id);

    const conn = this.room.getConnection(target.id);
    if (conn) {
      this.send(conn, { type: "kicked", byName: host.name });
      conn.close();
    }

    this.afterPlayerLeft(target.id);
  }

  private onTransferHost(
    msg: Extract<ClientMessage, { type: "transferHost" }>,
    sender: Party.Connection,
  ) {
    const host = this.requireHost(sender);
    if (!host) return;
    if (msg.playerId === sender.id) return;

    const target = this.players.get(msg.playerId);
    if (!target) {
      return this.sendError(sender, "unknown_player", "That player already left.");
    }

    host.isHost = false;
    target.isHost = true;
    this.broadcastSnapshot();
  }

  // --- round lifecycle -----------------------------------------------------

  private onStartGame(sender: Party.Connection) {
    if (!this.requireHost(sender)) return;

    if (this.phase !== "lobby") {
      return this.sendError(sender, "already_started", "The round has already begun.");
    }
    if (this.players.size < MIN_PLAYERS) {
      return this.sendError(
        sender,
        "not_enough_players",
        `Need at least ${MIN_PLAYERS} players to start.`,
      );
    }

    this.assignRoles();
    this.phase = "playing";
    this.setDeadline(envMs(this.room.env, "ROUND_MS", ROUND_MS), () =>
      this.callMeeting(),
    );
    this.broadcastSnapshot();
  }

  /** Exactly one Hacker, chosen uniformly. Everyone else monitors. */
  private assignRoles() {
    const ids = [...this.players.keys()];
    const hackerId = ids[Math.floor(Math.random() * ids.length)];

    this.roles.clear();
    for (const id of ids) {
      const role: Role = id === hackerId ? "hacker" : "benign";
      this.roles.set(id, role);
      const conn = this.room.getConnection(id);
      // Per-connection, so no other client sees this message at all.
      if (conn) this.send(conn, { type: "role", role });
    }
  }

  private callMeeting() {
    if (this.phase !== "playing") return;
    this.phase = "meeting";
    this.votes.clear();
    this.setDeadline(envMs(this.room.env, "MEETING_MS", MEETING_MS), () =>
      this.endRound(),
    );
    this.broadcastSnapshot();
  }

  private endRound() {
    if (this.phase === "ended") return;

    const tally = new Map<string, number>();
    for (const target of this.votes.values()) {
      if (target === null) continue;
      tally.set(target, (tally.get(target) ?? 0) + 1);
    }

    // A tie ejects nobody, exactly like a skip.
    let ejectedId: string | null = null;
    let best = 0;
    let tied = false;
    for (const [id, n] of tally) {
      if (n > best) {
        best = n;
        ejectedId = id;
        tied = false;
      } else if (n === best) {
        tied = true;
      }
    }
    if (tied || best === 0) ejectedId = null;

    const hackerId = [...this.roles.entries()].find(([, r]) => r === "hacker")?.[0] ?? "";
    const hacker = this.players.get(hackerId);
    const ejected = ejectedId ? this.players.get(ejectedId) : null;

    const hits = [...this.players.values()]
      .filter((p) => this.roles.get(p.id) === "benign")
      .map((p) => {
        const flags = this.flaggedBy.get(p.id) ?? new Set<number>();
        let hit = 0;
        for (const seq of flags) if (this.anomalySeqs.has(seq)) hit++;
        return { playerId: p.id, name: p.name, hits: hit, misses: flags.size - hit };
      })
      .sort((a, b) => b.hits - a.hits || a.misses - b.misses);

    this.result = {
      hackerId,
      hackerName: hacker?.name ?? "(left the room)",
      ejectedId,
      ejectedName: ejected?.name ?? null,
      benignWin: ejectedId !== null && ejectedId === hackerId,
      hits,
      attacksLaunched: this.attacksLaunched,
    };

    this.phase = "ended";
    this.clearDeadline();
    this.broadcastSnapshot();
  }

  private setDeadline(ms: number, onExpiry: () => void) {
    this.clearDeadline();
    this.deadline = Date.now() + ms;
    this.phaseTimer = setTimeout(onExpiry, ms);
  }

  private clearDeadline() {
    if (this.phaseTimer) clearTimeout(this.phaseTimer);
    this.phaseTimer = null;
    this.deadline = null;
  }

  // --- the feed ------------------------------------------------------------

  /**
   * Traffic arrives from the host's browser and fans out from here. This is the
   * single point where role filtering happens, which is why it is not possible
   * for the Hacker to see the feed by tampering with their own client.
   */
  private onFeed(
    msg: Extract<ClientMessage, { type: "feed" }>,
    sender: Party.Connection,
  ) {
    const host = this.players.get(sender.id);
    if (!host?.isHost) return this.sendError(sender, "not_host", "Only the host feeds.");
    if (this.phase !== "playing") return;
    if (!Array.isArray(msg.packets)) return;

    const clean: Packet[] = [];
    for (const raw of msg.packets) {
      const { anomaly, ...packet } = raw;
      if (anomaly) this.trackAnomaly(packet.seq, anomaly);
      this.recentPackets.set(packet.seq, packet);
      clean.push(packet);
    }
    this.trimTracked();

    for (const conn of this.room.getConnections()) {
      if (this.roles.get(conn.id) !== "benign") continue;
      this.send(conn, { type: "packets", packets: clean });
    }
  }

  private trackAnomaly(seq: number, kind: AttackKind) {
    this.anomalySeqs.set(seq, kind);
    this.seenSeqs.push(seq);
  }

  private trimTracked() {
    while (this.seenSeqs.length > MAX_TRACKED_SEQS) {
      const old = this.seenSeqs.shift();
      if (old !== undefined) this.anomalySeqs.delete(old);
    }
    // recentPackets only needs to cover what someone might still flag.
    if (this.recentPackets.size > MAX_TRACKED_SEQS) {
      const cutoff = this.recentPackets.size - MAX_TRACKED_SEQS;
      let i = 0;
      for (const key of this.recentPackets.keys()) {
        if (i++ >= cutoff) break;
        this.recentPackets.delete(key);
      }
    }
  }

  // --- hacker actions ------------------------------------------------------

  private onAttack(
    msg: Extract<ClientMessage, { type: "attack" }>,
    sender: Party.Connection,
  ) {
    if (this.phase !== "playing") {
      return this.sendError(sender, "wrong_phase", "Not during a round.");
    }
    if (this.roles.get(sender.id) !== "hacker") {
      return this.sendError(sender, "not_hacker", "You are not the hacker.");
    }

    const kind = msg.kind;
    if (kind !== "spoof" && kind !== "disrupt" && kind !== "takeover") {
      return this.sendError(sender, "bad_message", "Unknown attack.");
    }

    const now = Date.now();
    if (now - this.lastAttackAt < GLOBAL_ATTACK_COOLDOWN_MS) {
      return this.sendError(sender, "on_cooldown", "Too soon after your last attack.");
    }
    if (now - (this.lastAttackByKind.get(kind) ?? -Infinity) < ATTACK_COOLDOWN_MS) {
      return this.sendError(sender, "on_cooldown", "That attack is still recharging.");
    }

    this.lastAttackAt = now;
    this.lastAttackByKind.set(kind, now);
    this.attacksLaunched++;

    // A takeover also seizes one Benign player's screen for a few seconds.
    let victimLabel: string | undefined;
    if (kind === "takeover") {
      const candidates = [...this.players.keys()].filter(
        (id) => this.roles.get(id) === "benign",
      );
      const victimId = candidates[Math.floor(Math.random() * candidates.length)];
      const victim = victimId ? this.room.getConnection(victimId) : null;
      if (victim) {
        this.send(victim, { type: "takeover", untilMs: now + TAKEOVER_MS });
      }
      victimLabel = this.players.get(victimId ?? "")?.name;
    }

    // Ask the host's generator to splice it in. Deliberately anonymous: the
    // host learns an attack happened, never who ordered it.
    const hostId = [...this.players.values()].find((p) => p.isHost)?.id;
    const hostConn = hostId ? this.room.getConnection(hostId) : null;
    if (hostConn) this.send(hostConn, { type: "inject", kind, victimLabel });
  }

  // --- benign actions ------------------------------------------------------

  private onFlag(
    msg: Extract<ClientMessage, { type: "flag" }>,
    sender: Party.Connection,
  ) {
    if (this.phase !== "playing") {
      return this.sendError(sender, "wrong_phase", "Not during a round.");
    }
    if (this.roles.get(sender.id) !== "benign") {
      return this.sendError(sender, "bad_message", "Only analysts can flag.");
    }

    const player = this.players.get(sender.id);
    if (!player) return;

    let flags = this.flaggedBy.get(sender.id);
    if (!flags) this.flaggedBy.set(sender.id, (flags = new Set()));
    if (flags.has(msg.seq)) return; // Already flagged; not an error, just a no-op.
    flags.add(msg.seq);

    const kind = this.anomalySeqs.get(msg.seq) ?? null;
    const hit = kind !== null;
    const packet = this.recentPackets.get(msg.seq);

    if (packet) {
      this.evidence.push({
        seq: msg.seq,
        packet,
        byId: sender.id,
        byName: player.name,
        hit,
        kind,
      });
      if (this.evidence.length > MAX_EVIDENCE) this.evidence.shift();
    }

    this.send(sender, { type: "flagAck", seq: msg.seq, hit });
  }

  private onVote(
    msg: Extract<ClientMessage, { type: "vote" }>,
    sender: Party.Connection,
  ) {
    if (this.phase !== "meeting") {
      return this.sendError(sender, "wrong_phase", "There is no vote open.");
    }
    if (!this.players.has(sender.id)) return;
    if (msg.targetId !== null && !this.players.has(msg.targetId)) {
      return this.sendError(sender, "unknown_player", "That player is not here.");
    }

    this.votes.set(sender.id, msg.targetId);
    this.broadcastSnapshot();

    // Everyone has spoken, so there is nothing left to wait for.
    if (this.votes.size >= this.players.size) this.endRound();
  }

  // --- membership ----------------------------------------------------------

  onClose(conn: Party.Connection) {
    if (this.players.delete(conn.id)) this.afterPlayerLeft(conn.id);
  }

  onError(conn: Party.Connection) {
    if (this.players.delete(conn.id)) this.afterPlayerLeft(conn.id);
  }

  /**
   * Losing a player can end a round outright. The Hacker leaving is the obvious
   * case: there is no longer anyone to catch, so the round is over rather than
   * quietly unwinnable.
   */
  private afterPlayerLeft(id: string) {
    this.ensureHost();
    this.votes.delete(id);

    if (this.phase === "playing" || this.phase === "meeting") {
      if (this.roles.get(id) === "hacker") {
        this.endRound();
        return;
      }
      if (this.players.size < MIN_PLAYERS) {
        this.endRound();
        return;
      }
      if (this.phase === "meeting" && this.votes.size >= this.players.size) {
        this.endRound();
        return;
      }
    }

    this.broadcastSnapshot();
  }

  private ensureHost() {
    if (this.players.size === 0) return;
    const hosts = [...this.players.values()].filter((p) => p.isHost);
    if (hosts.length === 1) return;

    for (const p of this.players.values()) p.isHost = false;
    const [first] = hosts.length > 1 ? hosts : [...this.players.values()];
    first.isHost = true;
  }

  private requireHost(sender: Party.Connection): Player | null {
    const player = this.players.get(sender.id);
    if (!player?.isHost) {
      this.sendError(sender, "not_host", "Only the host can do that.");
      return null;
    }
    return player;
  }

  // --- plumbing ------------------------------------------------------------

  private snapshot(): RoomSnapshot {
    return {
      code: this.room.id,
      phase: this.phase,
      players: [...this.players.values()],
      deadline: this.deadline,
      // Evidence is the point of the meeting, so it stays hidden until then.
      evidence: this.phase === "meeting" || this.phase === "ended" ? this.evidence : [],
      votes: this.phase === "meeting" ? this.voteList() : [],
      result: this.result,
    };
  }

  private voteList(): Vote[] {
    return [...this.votes.entries()].map(([voterId, targetId]) => ({ voterId, targetId }));
  }

  private broadcastSnapshot() {
    const room = this.snapshot();
    for (const conn of this.room.getConnections()) {
      if (this.banned.has(conn.id)) continue;
      this.send(conn, { type: "snapshot", room, youId: conn.id });
    }
  }

  private sendError(conn: Party.Connection, code: ErrorCode, message: string) {
    this.send(conn, { type: "error", code, message });
  }

  private send(conn: Party.Connection, msg: ServerMessage) {
    conn.send(JSON.stringify(msg));
  }
}

NetsleuthRoom satisfies Party.Worker;
